baseURL = 'https://kerkhof.dev/'
locale = 'en-US'
title = "Joseph Kerkhof"
canonifyURLs = true

[markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false
    lineNos = false
    tabWidth = 4

enableEmoji = true # https://www.webfx.com/tools/emoji-cheat-sheet/
enableRobotsTXT = true

[pagination]
pagerSize = 4

[params]
	description = "Joseph Kerkhof is a senior backend engineer specializing in PHP, Laravel, distributed architectures, AI workflows, and cloud systems."
	cloudflareAnalyticsToken = "bc214cbe4671420b9be3206eeaf176ac"
	mainSections = ["posts"]
	mediaBaseURL = "https://media.kerkhof.dev"
	motto = "Soli Deo gloria"

[params.author]
    name = "Joseph Kerkhof"
    email = "joseph@kerkhof.dev"
    github = "josephkerkhof"

[[params.social]]
    name = "X"
    icon = "twitter"
    url = "https://x.com/josephkerkhof"
[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://www.linkedin.com/in/josephkerkhof/"
[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/josephkerkhof"
[[params.social]]
    name = "GitLab"
    icon = "gitlab"
    url = "https://gitlab.com/josephkerkhof/"
[[params.social]]
    name = "RSS"
    icon = "rss"
    url = "https://kerkhof.dev/index.xml"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "all posts"
    title = "All Posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "tags"
    title = "Tags"
    url = "/tags"
    weight = 3

[[menu.main]]
    name = "fun"
    title = "Fun"
    url = "/fun"
    weight = 4

[[menu.main]]
    name = "resume"
    title = "Resume"
    url = "https://raw.githubusercontent.com/josephkerkhof/resume/master/Joseph_Kerkhof.pdf"
    weight = 5

[[menu.main]]
    name = "now"
    title = "Now"
    url = "/now"
    weight = 6
